"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#445682)\
$os\
[](bg:#dc5367 fg:#445682)\
$username\
[](bg:#fe6156 fg:#dc5367)\
$directory\
[](fg:#fe6156 bg:#FF9B9B)\
$git_branch\
$git_status\
[](fg:#FF9B9B bg:#AC87C5)\
$python\
$nodejs\
$swift\
$rust\
$golang\
$php\
$ruby\
$julia\
[](fg:#AC87C5 bg:#6E85B7)\
$time\
$battery\
[](fg:#6E85B7)\
$line_break$character"""

[os]
disabled = false
style = "bg:#445682 fg:#f0fff0"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[username]
show_always = true
style_user = "fg:#f0fff0 bg:#dc5367"
style_root = "fg:#f0fff0 bg:#dc5367"
format = '[ $user ]($style)'

[directory]
style = "fg:#f0fff0 bg:#fe6156"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#E0AED0"
format = '[[ $symbol $branch ](fg:#f0fff0 bg:#FF9B9B)]($style)'

[git_status]
style = "bg:#E0AED0"
format = '[[($all_status$ahead_behind )](fg:#f0fff0 bg:#FF9B9B)]($style)'

[python]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[nodejs]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[rust]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[golang]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[php]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[ruby]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[julia]
symbol = ""
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[java]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[swift]
symbol = " "
style = "bg:#AC87C5"
format = '[[ $symbol ($version) ](fg:#f0fff0 bg:#AC87C5)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[✧˚·. $time ✧˚·.](fg:#FDF4F5 bg:#6E85B7)]($style)'

[battery]
disabled = false
full_symbol = '󰁹'
charging_symbol = '󰂄 '
discharging_symbol = '󰂃'
empty_symbol = '󰂎'
format = '[$symbol$percentage]($style)'

[[battery.display]]
threshold = 10
style = 'fg:#ff0038 bg:#6E85B7'

[[battery.display]]
threshold = 30
style = "fg:#FFB000 bg:#6E85B7"

[[battery.display]]
threshold = 100
style = "fg:#9ADE7B bg:#6E85B7"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[❯](#f0fff0)"
error_symbol = '[❯](#fe6156)'
vimcmd_symbol = '[](#50c878)'
